package com.dante.paul.dd5erandomlootgenerator.MagicItem2024;

public final class RelicsTables {

    private RelicsTables() {}

    public static final MagicItem2024Table COMMON = new MagicItem2024Table()
            .add(1, 8, "Ear Horn of Hearing")
            .add(9, 28, "Potion of Healing")
            .add(29, 36, "Pot of Awakening")
            .add(37, 44, "Ruby of the War Mage")
            .add(45, 52, "Shield of Expression")
            .add(53, 60, "Smoldering Armor")
            .add(61, 80, "Spell Scroll (cantrip or level 1 spell)")
            .add(81, 90, "Staff of Adornment")
            .add(91, 100, "Staff of Flowers");

    public static final MagicItem2024Table UNCOMMON = new MagicItem2024Table()
            .add(1, 5, "Enspelled Staff (cantrip or level 1 spell)")
            .add(6, 10, "Keoghtom's Ointment")
            .add(11, 15, "Mariner's Armor")
            .add(16, 20, "Nature's Mantle")
            .add(21, 25, "Pearl of Power")
            .add(26, 30, "Periapt of Health")
            .add(31, 35, "Periapt of Wound Closure")
            .add(36, 40, "Potion of Animal Friendship")
            .add(41, 55, "Potion of Healing (greater)")
            .add(56, 60, "Potion of Resistance")
            .add(61, 65, "Ring of Water Walking")
            .add(66, 70, "Sending Stones")
            .add(71, 80, "Spell Scroll (level 2 or level 3 spell)")
            .add(81, 85, "Staff of the Adder")
            .add(86, 90, "Staff of the Python")
            .add(91, 95, "Wand of Magic Detection")
            .add(96, 100, "Wand of the War Mage, +1");

    public static final MagicItem2024Table RARE = new MagicItem2024Table()
            .add(1, 3, "Amulet of Health")
            .add(4, 7, "Armor, +1")
            .add(8, 9, "Bowl of Commanding Water Elementals")
            .add(10, 11, "Brazier of Commanding Fire Elementals")
            .add(12, 13, "Censer of Controlling Air Elementals")
            .add(14, 16, "Elixir of Health")
            .add(17, 19, "Enspelled Staff (level 2 or 3 spell)")
            .add(20, 22, "Horn of Blasting")
            .add(23, 25, "Horn of Valhalla (brass or silver)")
            .add(26, 28, "Ioun Stone (reserve or sustenance)")
            .add(29, 31, "Mace of Disruption")
            .add(32, 34, "Mace of Smiting")
            .add(35, 37, "Mace of Terror")
            .add(38, 40, "Necklace of Prayer Beads")
            .add(41, 43, "Periapt of Proof against Poison")
            .add(44, 51, "Potion of Healing (superior)")
            .add(52, 54, "Ring of Animal Influence")
            .add(55, 58, "Ring of Resistance")
            .add(59, 61, "Ring of Spell Storing")
            .add(62, 65, "Scroll of Protection")
            .add(66, 73, "Spell Scroll (level 4 or level 5 spell)")
            .add(74, 76, "Staff of Charming")
            .add(77, 79, "Staff of Healing")
            .add(80, 82, "Staff of Swarming Insects")
            .add(83, 85, "Staff of the Woodlands")
            .add(86, 88, "Staff of Withering")
            .add(89, 90, "Stone of Controlling Earth Elementals")
            .add(91, 93, "Tentacle Rod")
            .add(94, 96, "Wand of Paralysis")
            .add(97, 100, "Wand of the War Mage, +2");

    public static final MagicItem2024Table VERY_RARE = new MagicItem2024Table()
            .add(1, 5, "Armor, +2")
            .add(6, 10, "Candle of Invocation")
            .add(11, 15, "Cauldron of Rebirth")
            .add(16, 20, "Enspelled Staff (level 4 or 5 spell)")
            .add(21, 25, "Horn of Valhalla (bronze)")
            .add(26, 30, "Ioun Stone (insight)")
            .add(31, 35, "Manual of Bodily Health")
            .add(36, 43, "Potion of Healing (supreme)")
            .add(44, 50, "Potion of Vitality")
            .add(51, 55, "Rod of Alertness")
            .add(56, 65, "Spell Scroll (level 6, level 7, or level 8 spell)")
            .add(66, 70, "Spirit Board")
            .add(71, 75, "Staff of Fire")
            .add(76, 80, "Staff of Frost")
            .add(81, 85, "Staff of Striking")
            .add(86, 90, "Staff of Thunder and Lightning")
            .add(91, 95, "Tome of Understanding")
            .add(96, 100, "Wand of the War Mage, +3");

    public static final MagicItem2024Table LEGENDARY = new MagicItem2024Table()
            .add(1, 8, "Armor of Invulnerability")
            .add(9, 18, "Armor, +3")
            .add(19, 27, "Enspelled Staff (level 6, 7, or 8 spell)")
            .add(28, 36, "Holy Avenger")
            .add(37, 45, "Horn of Valhalla (iron)")
            .add(46, 54, "Rod of Resurrection")
            .add(55, 63, "Scarab of Protection")
            .add(64, 72, "Scroll of Titan Summoning")
            .add(73, 80, "Spell Scroll (level 9 spell)")
            .add(81, 90, "Talisman of Pure Good")
            .add(91, 100, "Talisman of Ultimate Evil");
}
