package com.verdantsoftware.lootforge.MagicItem2024;

public final class ArcanaTables {

    private ArcanaTables() {}

    public static final MagicItem2024Table COMMON = new MagicItem2024Table()
            .add(1, 2, "Bead of Nourishment")
            .add(3, 4, "Bead of Refreshment")
            .add(5, 7, "Candle of the Deep")
            .add(8, 10, "Cloak of Billowing")
            .add(11, 13, "Cloak of Many Fashions")
            .add(14, 15, "Clothes of Mending")
            .add(16, 17, "Dark Shard Amulet")
            .add(18, 19, "Enduring Spellbook")
            .add(20, 21, "Ersatz Eye")
            .add(22, 24, "Hat of Vermin")
            .add(25, 27, "Hat of Wizardry")
            .add(28, 29, "Heward's Handy Spice Pouch")
            .add(30, 31, "Horn of Silent Alarm")
            .add(32, 33, "Instrument of Illusions")
            .add(34, 35, "Instrument of Scribing")
            .add(36, 37, "Lock of Trickery")
            .add(38, 40, "Mystery Key")
            .add(41, 42, "Orb of Direction")
            .add(43, 44, "Orb of Time")
            .add(45, 46, "Perfume of Bewitching")
            .add(47, 49, "Pipe of Smoke Monsters")
            .add(50, 52, "Potion of Climbing")
            .add(53, 55, "Potion of Comprehension")
            .add(56, 58, "Pot of Awakening")
            .add(59, 60, "Prosthetic Limb")
            .add(61, 64, "Rival Coin")
            .add(65, 66, "Rope of Mending")
            .add(67, 68, "Ruby of the War Mage")
            .add(69, 82, "Spell Scroll (cantrip or level 1 spell)")
            .add(83, 84, "Staff of Adornment")
            .add(85, 86, "Staff of Birdcalls")
            .add(87, 89, "Staff of Flowers")
            .add(90, 92, "Talking Doll")
            .add(93, 94, "Tankard of Sobriety")
            .add(95, 97, "Wand of Conducting")
            .add(98, 100, "Wand of Pyrotechnics");

    public static final MagicItem2024Table UNCOMMON = new MagicItem2024Table()
            .add(1, 1, "Amulet of Proof against Detection and Location")
            .add(2, 2, "Baba Yaga's Dancing Broom")
            .add(3, 5, "Bag of Holding")
            .add(6, 7, "Bag of Tricks")
            .add(8, 8, "Brooch of Shielding")
            .add(9, 9, "Broom of Flying")
            .add(10, 10, "Cap of Water Breathing")
            .add(11, 11, "Circlet of Blasting")
            .add(12, 13, "Cloak of Protection")
            .add(14, 14, "Cloak of the Manta Ray")
            .add(15, 15, "Decanter of Endless Water")
            .add(16, 16, "Deck of Illusions")
            .add(17, 18, "Driftglobe")
            .add(19, 20, "Dust of Disappearance")
            .add(21, 21, "Dust of Dryness")
            .add(22, 22, "Dust of Sneezing and Choking")
            .add(23, 24, "Elemental Gem")
            .add(25, 25, "Enspelled Staff (cantrip or level 1 spell)")
            .add(26, 26, "Eversmoking Bottle")
            .add(27, 27, "Eyes of Charming")
            .add(28, 28, "Eyes of Minute Seeing")
            .add(29, 30, "Figurine of Wondrous Power (silver raven)")
            .add(31, 31, "Gem of Brightness")
            .add(32, 32, "Hag Eye")
            .add(33, 33, "Hat of Disguise")
            .add(34, 34, "Headband of Intellect")
            .add(35, 35, "Helm of Comprehending Languages")
            .add(36, 36, "Helm of Telepathy")
            .add(37, 37, "Immovable Rod")
            .add(38, 38, "Lantern of Revealing")
            .add(39, 39, "Medallion of Thoughts")
            .add(40, 40, "Mithral Armor")
            .add(41, 42, "Necklace of Adaptation")
            .add(43, 43, "Oil of Slipperiness")
            .add(44, 44, "Pearl of Power")
            .add(45, 45, "Periapt of Health")
            .add(46, 47, "Philter of Love")
            .add(48, 49, "Potion of Animal Friendship")
            .add(50, 51, "Potion of Fire Breath")
            .add(52, 53, "Potion of Giant Strength (hill)")
            .add(54, 55, "Potion of Growth")
            .add(56, 57, "Potion of Poison")
            .add(58, 59, "Potion of Resistance")
            .add(60, 61, "Potion of Water Breathing")
            .add(62, 62, "Quaal's Feather Token (anchor, fan, or tree)")
            .add(63, 63, "Ring of Mind Shielding")
            .add(64, 65, "Robe of Useful Items")
            .add(66, 67, "Rod of the Pact Keeper, +1")
            .add(68, 69, "Rope of Climbing")
            .add(70, 70, "Saddle of the Cavalier")
            .add(71, 72, "Sending Stones")
            .add(73, 74, "Slippers of Spider Climbing")
            .add(75, 82, "Spell Scroll (level 2 or level 3 spell)")
            .add(83, 83, "Staff of the Adder")
            .add(84, 84, "Staff of the Python")
            .add(85, 88, "Wand of Magic Detection")
            .add(89, 91, "Wand of Magic Missiles")
            .add(92, 93, "Wand of Secrets")
            .add(94, 95, "Wand of the War Mage, +1")
            .add(96, 97, "Wand of Web")
            .add(98, 99, "Wind Fan")
            .add(100, 100, "Winged Boots");

    public static final MagicItem2024Table RARE = new MagicItem2024Table()
            .add(1, 1, "Bag of Beans")
            .add(2, 3, "Bead of Force")
            .add(4, 4, "Bowl of Commanding Water Elementals")
            .add(5, 6, "Bracers of Defense")
            .add(7, 7, "Brazier of Commanding Fire Elementals")
            .add(8, 9, "Cape of the Mountebank")
            .add(10, 10, "Censer of Controlling Air Elementals")
            .add(11, 12, "Chime of Opening")
            .add(13, 14, "Cloak of Displacement")
            .add(15, 16, "Cloak of the Bat")
            .add(17, 17, "Cube of Force")
            .add(18, 18, "Cube of Summoning")
            .add(19, 19, "Daern's Instant Fortress")
            .add(20, 21, "Enspelled Staff (level 2 or 3 spell)")
            .add(22, 23, "Figurine of Wondrous Power (bronze griffon, ebony fly, golden lions, ivory goats, marble elephant, onyx dog, or serpentine owl)")
            .add(24, 25, "Folding Boat")
            .add(26, 27, "Gem of Seeing")
            .add(28, 28, "Helm of Teleportation")
            .add(29, 30, "Heward's Handy Haversack")
            .add(31, 32, "Horseshoes of Speed")
            .add(33, 34, "Ioun Stone (reserve)")
            .add(35, 35, "Iron Bands of Bilarro")
            .add(36, 36, "Mantle of Spell Resistance")
            .add(37, 38, "Necklace of Fireballs")
            .add(39, 39, "Oil of Etherealness")
            .add(40, 40, "Portable Hole")
            .add(41, 42, "Potion of Clairvoyance")
            .add(43, 44, "Potion of Diminution")
            .add(45, 46, "Potion of Gaseous Form")
            .add(47, 47, "Potion of Giant Strength (fire)")
            .add(48, 49, "Potion of Giant Strength (frost or stone)")
            .add(50, 51, "Potion of Heroism")
            .add(52, 53, "Potion of Invisibility")
            .add(54, 55, "Potion of Invulnerability")
            .add(56, 57, "Potion of Mind Reading")
            .add(58, 59, "Quaal's Feather Token (bird, swan boat, or whip)")
            .add(60, 61, "Ring of Feather Falling")
            .add(62, 62, "Ring of Spell Storing")
            .add(63, 63, "Ring of X-ray Vision")
            .add(64, 65, "Robe of Eyes")
            .add(66, 66, "Rod of Rulership")
            .add(67, 68, "Rod of the Pact Keeper, +2")
            .add(69, 70, "Scroll of Protection")
            .add(71, 75, "Spell Scroll (level 4 or level 5 spell)")
            .add(76, 77, "Staff of Charming")
            .add(78, 79, "Staff of Swarming Insects")
            .add(80, 81, "Staff of Withering")
            .add(82, 82, "Stone of Controlling Earth Elementals")
            .add(83, 84, "Wand of Binding")
            .add(85, 86, "Wand of Fear")
            .add(87, 90, "Wand of Fireballs")
            .add(91, 94, "Wand of Lightning Bolts")
            .add(95, 96, "Wand of the War Mage, +2")
            .add(97, 98, "Wand of Wonder")
            .add(99, 100, "Wings of Flying");

    public static final MagicItem2024Table VERY_RARE = new MagicItem2024Table()
            .add(1, 2, "Amulet of the Planes")
            .add(3, 4, "Bag of Devouring")
            .add(5, 6, "Carpet of Flying")
            .add(7, 8, "Cauldron of Rebirth")
            .add(9, 10, "Cloak of Arachnida")
            .add(11, 12, "Crystal Ball")
            .add(13, 13, "Dancing Sword")
            .add(14, 14, "Efreeti Bottle")
            .add(15, 16, "Enspelled Staff (level 4 or 5 spell)")
            .add(17, 18, "Figurine of Wondrous Power (obsidian steed)")
            .add(19, 20, "Hat of Many Spells")
            .add(21, 22, "Helm of Brilliance")
            .add(23, 24, "Horseshoes of a Zephyr")
            .add(25, 26, "Ioun Stone (absorption, fortitude, intellect, or leadership)")
            .add(27, 28, "Manual of Golems (clay, flesh, iron, or stone)")
            .add(29, 29, "Mirror of Life Trapping")
            .add(30, 31, "Nolzur's Marvelous Pigments")
            .add(32, 34, "Oil of Sharpness")
            .add(35, 38, "Potion of Flying")
            .add(39, 42, "Potion of Giant Strength (cloud)")
            .add(43, 46, "Potion of Greater Invisibility")
            .add(47, 49, "Potion of Longevity")
            .add(50, 53, "Potion of Speed")
            .add(54, 57, "Potion of Vitality")
            .add(58, 59, "Ring of Regeneration")
            .add(60, 61, "Ring of Shooting Stars")
            .add(62, 63, "Ring of Telekinesis")
            .add(64, 65, "Robe of Scintillating Colors")
            .add(66, 67, "Robe of Stars")
            .add(68, 69, "Rod of Absorption")
            .add(70, 71, "Rod of Security")
            .add(72, 73, "Rod of the Pact Keeper, +3")
            .add(74, 85, "Spell Scroll (level 6, level 7, or level 8 spell)")
            .add(86, 87, "Staff of Fire")
            .add(88, 89, "Staff of Frost")
            .add(90, 90, "Staff of Power")
            .add(91, 92, "Staff of Thunder and Lightning")
            .add(93, 94, "Tome of Clear Thought")
            .add(95, 97, "Wand of Polymorph")
            .add(98, 100, "Wand of the War Mage, +3");

    public static final MagicItem2024Table LEGENDARY = new MagicItem2024Table()
            .add(1, 4, "Apparatus of Kwalish")
            .add(5, 8, "Cloak of Invisibility")
            .add(9, 12, "Crystal Ball of Mind Reading")
            .add(13, 16, "Crystal Ball of Telepathy")
            .add(17, 20, "Crystal Ball of True Seeing")
            .add(21, 22, "Cubic Gate")
            .add(23, 23, "Deck of Many Things")
            .add(24, 27, "Enspelled Staff (level 6, 7, or 8 spell)")
            .add(28, 31, "Ioun Stone (greater absorption, mastery, or regeneration)")
            .add(32, 33, "Iron Flask")
            .add(34, 41, "Potion of Storm Giant Strength (storm)")
            .add(42, 45, "Ring of Djinni Summoning")
            .add(46, 49, "Ring of Elemental Command (air, earth, fire, or water)")
            .add(50, 53, "Ring of Invisibility")
            .add(54, 57, "Ring of Spell Turning")
            .add(58, 58, "Ring of Three Wishes")
            .add(59, 59, "Robe of the Archmagi")
            .add(60, 61, "Scroll of Titan Summoning")
            .add(62, 65, "Sovereign Glue")
            .add(66, 83, "Spell Scroll (level 9 spell)")
            .add(84, 84, "Sphere of Annihilation")
            .add(85, 85, "Staff of the Magi")
            .add(86, 88, "Talisman of the Sphere")
            .add(89, 92, "Tome of the Stilled Tongue")
            .add(93, 96, "Universal Solvent")
            .add(97, 100, "Well of Many Worlds");
}
