package com.verdantsoftware.lootforge.MagicItem2024;

public final class ArmamentsTables {

    private ArmamentsTables() {}

    public static final MagicItem2024Table COMMON = new MagicItem2024Table()
            .add(1, 10, "Armor of Gleaming")
            .add(11, 20, "Cast-Off Armor")
            .add(21, 30, "Dread Helm")
            .add(31, 40, "Moon-Touched Sword")
            .add(41, 50, "Shield of Expression")
            .add(51, 60, "Silvered Weapon")
            .add(61, 70, "Smoldering Armor")
            .add(71, 80, "Sylvan Talon")
            .add(81, 90, "Veteran's Cane")
            .add(91, 100, "Walloping Ammunition");

    public static final MagicItem2024Table UNCOMMON = new MagicItem2024Table()
            .add(1, 4, "Adamantine Armor")
            .add(5, 8, "Adamantine Weapon")
            .add(9, 13, "Ammunition, +1")
            .add(14, 18, "Bracers of Archery")
            .add(19, 23, "Enspelled Armor (cantrip or level 1 spell)")
            .add(24, 28, "Enspelled Weapon (cantrip or level 1 spell)")
            .add(29, 33, "Gauntlets of Ogre Power")
            .add(34, 38, "Javelin of Lightning")
            .add(39, 43, "Mariner's Armor")
            .add(44, 48, "Mithral Armor")
            .add(49, 53, "Potion of Giant Strength (hill)")
            .add(54, 58, "Potion of Pugilism")
            .add(59, 62, "Quiver of Ehlonna")
            .add(63, 66, "Saddle of the Cavalier")
            .add(67, 71, "Sentinel Shield")
            .add(72, 76, "Shield, +1")
            .add(77, 81, "Sword of Vengeance")
            .add(82, 85, "Trident of Fish Command")
            .add(86, 90, "Weapon, +1")
            .add(91, 95, "Weapon of Warning")
            .add(96, 100, "Wraps of Unarmed Power, +1");

    public static final MagicItem2024Table RARE = new MagicItem2024Table()
            .add(1, 3, "Ammunition, +2")
            .add(4, 7, "Armor, +1")
            .add(8, 10, "Armor of Resistance")
            .add(11, 13, "Armor of Vulnerability")
            .add(14, 15, "Arrow-Catching Shield")
            .add(16, 18, "Belt of Giant Strength (hill)")
            .add(19, 20, "Berserker Axe")
            .add(21, 22, "Daern's Instant Fortress")
            .add(23, 25, "Dagger of Venom")
            .add(26, 28, "Dragon Slayer")
            .add(29, 31, "Elven Chain")
            .add(32, 34, "Enspelled Armor (level 2 or 3 spell)")
            .add(35, 37, "Enspelled Weapon (level 2 or 3 spell)")
            .add(38, 40, "Flame Tongue")
            .add(41, 43, "Giant Slayer")
            .add(44, 46, "Horn of Blasting")
            .add(47, 48, "Horn of Valhalla (brass or silver)")
            .add(49, 51, "Ioun Stone (protection)")
            .add(52, 54, "Mace of Disruption")
            .add(55, 57, "Mace of Smiting")
            .add(58, 60, "Mace of Terror")
            .add(61, 63, "Potion of Giant Strength (fire)")
            .add(64, 66, "Potion of Giant Strength (frost or stone)")
            .add(67, 69, "Potion of Heroism")
            .add(70, 72, "Potion of Invulnerability")
            .add(73, 75, "Ring of Protection")
            .add(76, 78, "Ring of the Ram")
            .add(79, 81, "Shield, +2")
            .add(82, 84, "Shield of Missile Attraction")
            .add(85, 86, "Sun Blade")
            .add(87, 88, "Sword of Life Stealing")
            .add(89, 90, "Sword of Wounding")
            .add(91, 92, "Tentacle Rod")
            .add(93, 94, "Vicious Weapon")
            .add(95, 97, "Weapon, +2")
            .add(98, 100, "Wraps of Unarmed Power, +2");

    public static final MagicItem2024Table VERY_RARE = new MagicItem2024Table()
            .add(1, 3, "Ammunition, +3")
            .add(4, 6, "Ammunition of Slaying")
            .add(7, 9, "Animated Shield")
            .add(10, 12, "Armor, +2")
            .add(13, 14, "Belt of Giant Strength (fire)")
            .add(15, 17, "Belt of Giant Strength (frost or stone)")
            .add(18, 19, "Dancing Sword")
            .add(20, 22, "Demon Armor")
            .add(23, 25, "Dragon Scale Mail")
            .add(26, 28, "Dwarven Plate")
            .add(29, 31, "Dwarven Thrower")
            .add(32, 34, "Energy Bow")
            .add(35, 37, "Enspelled Armor (level 4 or 5 spell)")
            .add(38, 40, "Enspelled Weapon (level 4 or 5 spell)")
            .add(41, 43, "Executioner's Axe")
            .add(44, 46, "Frost Brand")
            .add(47, 49, "Horn of Valhalla (bronze)")
            .add(50, 52, "Ioun Stone (strength)")
            .add(53, 55, "Lute of Thunderous Thumping")
            .add(56, 58, "Manual of Gainful Exercise")
            .add(59, 61, "Nine Lives Stealer")
            .add(62, 64, "Oathbow")
            .add(65, 68, "Oil of Sharpness")
            .add(69, 72, "Potion of Giant Strength (cloud)")
            .add(73, 75, "Quarterstaff of the Acrobat")
            .add(76, 78, "Scimitar of Speed")
            .add(79, 82, "Shield, +3")
            .add(83, 85, "Shield of the Cavalier")
            .add(86, 88, "Spellguard Shield")
            .add(89, 91, "Sword of Sharpness")
            .add(92, 94, "Thunderous Greatclub")
            .add(95, 97, "Weapon, +3")
            .add(98, 100, "Wraps of Unarmed Power, +3");

    public static final MagicItem2024Table LEGENDARY = new MagicItem2024Table()
            .add(1, 6, "Armor, +3")
            .add(7, 12, "Armor of Invulnerability")
            .add(13, 18, "Belt of Giant Strength (cloud)")
            .add(19, 21, "Belt of Giant Strength (storm)")
            .add(22, 27, "Defender")
            .add(28, 33, "Efreeti Chain")
            .add(34, 39, "Enspelled Armor (level 6, 7, or 8 spell)")
            .add(40, 45, "Enspelled Weapon (level 6, 7, or 8 spell)")
            .add(46, 51, "Hammer of Thunderbolts")
            .add(52, 56, "Holy Avenger")
            .add(57, 62, "Horn of Valhalla (iron)")
            .add(63, 68, "Luck Blade")
            .add(69, 72, "Moonblade")
            .add(73, 78, "Plate Armor of Etherealness")
            .add(79, 87, "Potion of Giant Strength (storm)")
            .add(88, 90, "Rod of Lordly Might")
            .add(91, 95, "Sword of Answering")
            .add(96, 100, "Vorpal Sword");
}
