package com.verdantsoftware.lootforge.MagicItem2024;

public final class ImplementsTables {

    private ImplementsTables() {}

    public static final MagicItem2024Table COMMON = new MagicItem2024Table()
            .add(1, 2, "Bead of Nourishment")
            .add(3, 4, "Bead of Refreshment")
            .add(5, 6, "Boots of False Tracks")
            .add(7, 8, "Candle of the Deep")
            .add(9, 10, "Charlatan's Die")
            .add(11, 13, "Cloak of Many Fashions")
            .add(14, 15, "Clockwork Amulet")
            .add(16, 17, "Ear Horn of Hearing")
            .add(18, 19, "Ersatz Eye")
            .add(20, 21, "Heward's Handy Spice Pouch")
            .add(22, 23, "Horn of Silent Alarm")
            .add(24, 25, "Instrument of Illusions")
            .add(26, 27, "Instrument of Scribing")
            .add(28, 29, "Lock of Trickery")
            .add(30, 32, "Moon-Touched Sword")
            .add(33, 34, "Mystery Key")
            .add(35, 36, "Orb of Direction")
            .add(37, 38, "Orb of Time")
            .add(39, 40, "Perfume of Bewitching")
            .add(41, 42, "Pipe of Smoke Monsters")
            .add(43, 44, "Pole of Angling")
            .add(45, 46, "Pole of Collapsing")
            .add(47, 52, "Potion of Climbing")
            .add(53, 58, "Potion of Comprehension")
            .add(59, 74, "Potion of Healing")
            .add(75, 76, "Prosthetic Limb")
            .add(77, 78, "Rope of Mending")
            .add(79, 80, "Staff of Birdcalls")
            .add(81, 82, "Sylvan Talon")
            .add(83, 84, "Talking Doll")
            .add(85, 86, "Tankard of Sobriety")
            .add(87, 90, "Veteran's Cane")
            .add(91, 92, "Walloping Ammunition")
            .add(93, 94, "Wand of Conducting")
            .add(95, 97, "Wand of Enemy Detection")
            .add(98, 100, "Wand of Pyrotechnics");

    public static final MagicItem2024Table UNCOMMON = new MagicItem2024Table()
            .add(1, 2, "Alchemy Jug")
            .add(3, 6, "Ammunition, +1")
            .add(7, 10, "Bag of Holding")
            .add(11, 12, "Boots of Elvenkind")
            .add(13, 14, "Boots of Striding and Springing")
            .add(15, 16, "Boots of the Winterlands")
            .add(17, 18, "Broom of Flying")
            .add(19, 20, "Cap of Water Breathing")
            .add(21, 22, "Cloak of Elvenkind")
            .add(23, 24, "Cloak of Protection")
            .add(25, 26, "Cloak of the Manta Ray")
            .add(27, 27, "Decanter of Endless Water")
            .add(28, 30, "Driftglobe")
            .add(31, 32, "Dust of Disappearance")
            .add(33, 34, "Dust of Dryness")
            .add(35, 36, "Dust of Sneezing and Choking")
            .add(37, 38, "Enspelled Weapon (cantrip or level 1 spell)")
            .add(39, 40, "Eyes of Minute Seeing")
            .add(41, 42, "Eyes of the Eagle")
            .add(43, 44, "Gloves of Missile Snaring")
            .add(45, 46, "Gloves of Swimming and Climbing")
            .add(47, 48, "Gloves of Thievery")
            .add(49, 50, "Goggles of Night")
            .add(51, 51, "Hag Eye")
            .add(52, 54, "Helm of Comprehending Languages")
            .add(55, 55, "Immovable Rod")
            .add(56, 57, "Instrument of the Bards (Doss lute, Fochlucan bandore, or Mac-Fuirmidh cittern)")
            .add(58, 59, "Lantern of Revealing")
            .add(60, 61, "Nature's Mantle")
            .add(62, 63, "Oil of Slipperiness")
            .add(64, 65, "Pipes of Haunting")
            .add(66, 67, "Pipes of the Sewers")
            .add(68, 71, "Potion of Growth")
            .add(72, 80, "Potion of Healing (greater)")
            .add(81, 84, "Potion of Water Breathing")
            .add(85, 86, "Quaal's Feather Token (anchor, fan, or tree)")
            .add(87, 88, "Ring of Jumping")
            .add(89, 90, "Ring of Swimming")
            .add(91, 92, "Ring of Warmth")
            .add(93, 94, "Robe of Useful Items")
            .add(95, 96, "Rope of Climbing")
            .add(97, 98, "Stone of Good Luck")
            .add(99, 100, "Wand of Secrets");

    public static final MagicItem2024Table RARE = new MagicItem2024Table()
            .add(1, 4, "Ammunition, +2")
            .add(5, 8, "Bag of Beans")
            .add(9, 12, "Belt of Dwarvenkind")
            .add(13, 16, "Boots of Levitation")
            .add(17, 20, "Boots of Speed")
            .add(21, 24, "Chime of Opening")
            .add(25, 28, "Dimensional Shackles")
            .add(29, 32, "Enspelled Weapon (level 2 or 3 spell)")
            .add(33, 36, "Folding Boat")
            .add(37, 40, "Glamoured Studded Leather")
            .add(41, 44, "Heward's Handy Haversack")
            .add(45, 48, "Horseshoes of Speed")
            .add(49, 52, "Instrument of the Bards (Canaith mandolin or Cli lyre)")
            .add(53, 56, "Ioun Stone (awareness)")
            .add(57, 60, "Portable Hole")
            .add(61, 64, "Potion of Diminution")
            .add(65, 68, "Potion of Gaseous Form")
            .add(69, 76, "Potion of Healing (superior)")
            .add(77, 80, "Quaal's Feather Token (bird, swan boat, or whip)")
            .add(81, 84, "Ring of Evasion")
            .add(85, 88, "Ring of Free Action")
            .add(89, 92, "Rope of Entanglement")
            .add(93, 96, "Staff of Healing")
            .add(97, 100, "Wand of Enemy Detection");

    public static final MagicItem2024Table VERY_RARE = new MagicItem2024Table()
            .add(1, 7, "Ammunition, +3")
            .add(8, 14, "Bag of Devouring")
            .add(15, 21, "Carpet of Flying")
            .add(22, 28, "Enspelled Weapon (level 4 or 5 spell)")
            .add(29, 35, "Horseshoes of a Zephyr")
            .add(36, 42, "Instrument of the Bards (Anstruth harp)")
            .add(43, 49, "Ioun Stone (agility)")
            .add(50, 56, "Lute of Thunderous Thumping")
            .add(57, 63, "Manual of Quickness of Action")
            .add(64, 70, "Nolzur's Marvelous Pigments")
            .add(71, 77, "Potion of Flying")
            .add(78, 86, "Potion of Healing (supreme)")
            .add(87, 93, "Potion of Speed")
            .add(94, 100, "Tome of Leadership and Influence");

    public static final MagicItem2024Table LEGENDARY = new MagicItem2024Table()
            .add(1, 17, "Enspelled Weapon (level 6, 7, or 8 spell)")
            .add(18, 34, "Instrument of the Bards (Ollamh harp)")
            .add(35, 54, "Sovereign Glue")
            .add(55, 70, "Sphere of Annihilation")
            .add(71, 83, "Talisman of the Sphere")
            .add(84, 100, "Universal Solvent");
}
